// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.lj.nettysocket.proto;

public final class MsgProto {
  private MsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tmsg.proto\022\017google.protobuf\"C\n\003Msg\022\013\n\003u" +
      "id\030\001 \001(\005\022\021\n\treceiveId\030\002 \001(\005\022\017\n\007msgType\030\003" +
      " \001(\t\022\013\n\003msg\030\004 \001(\tB_\n\030com.lj.nettysocket." +
      "protoB\010MsgProtoP\001Z/google.golang.org/gen" +
      "proto/protobuf/ptype;ptype\242\002\005UTF-8b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_protobuf_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_Msg_descriptor,
        new String[] { "Uid", "ReceiveId", "MsgType", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
